# Site settings
author: Joshua Brancazio
title: From Espresso Shots to Data Plots
header-img: img/home-bg.png
email: joshua.brancazio@gmail.com
copyright_name: Joshua Brancazio
description: > # this means to ignore newlines until "baseurl:"
  Seeing the world through data-colored glasses
baseurl: "" # the subpath of your site, e.g. /blog
linkedin_username: joshua-brancazio
twitter_username: MrBroncosaurus
github_username:  Jbrancazio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
